name: booking_hotel
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logo.png
    - assets/Ellipse_1.png
    - assets/arrows_1.png
    - assets/google.png
    - assets/facebook.png
    - assets/apple.png
    - assets/bumimajapahit.png
    - assets/bumisurabaaya.png
    - assets/cari.png
    - assets/ciputra.png
    - assets/lokasi.png
    - assets/nav_awal.png
    - assets/notif.png
    - assets/other.png
    - assets/home.png
    - assets/mdi_location.png
    - assets/nav_2.png
    - assets/peta.png
    - assets/Rectangle 11.png
    - assets/Rectangle 12.png
    - assets/Rectangle 13.png
    - assets/Rectangle 14.png
    - assets/Rectangle 15.png
    - assets/Rectangle 16.png
    - assets/Vector.png
    - assets/Facilities.png
    - assets/Group.png
    - assets/heart.png
    - assets/carbon_area.png
    - assets/fluent-mdl2_breakfast.png
    - assets/material-symbols_bed.png
    - assets/mdi_bathroom.png
    - assets/streamline_hotel-air-conditioner.png
    - assets/tabler_wifi.png

  fonts:
    - family: InclusiveSans
      fonts:
        - asset: fonts/static/InclusiveSans-Regular.ttf
          weight: 400
        - asset: fonts/static/InclusiveSans-Medium.ttf
          weight: 500
        - asset: fonts/static/InclusiveSans-SemiBold.ttf
          weight: 600
        - asset: fonts/static/InclusiveSans-Bold.ttf
          weight: 700